# Generated by Django 4.2.1 on 2023-06-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('parish', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('parish_priest', models.CharField(blank=True, max_length=100, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='church', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
