# Generated by Django 4.2.1 on 2023-06-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_alter_church_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='creator',
        ),
    ]
