# Generated by Django 4.2.1 on 2023-06-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_formsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='is_respomded',
            new_name='is_responded',
        ),
    ]
